-- MySQL Script generated by MySQL Workbench
-- 05/30/15 16:35:33
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema YoLoArreglo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `YoLoArreglo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `YoLoArreglo` ;

-- -----------------------------------------------------
-- Table `YoLoArreglo`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YoLoArreglo`.`marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YoLoArreglo`.`modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YoLoArreglo`.`modelos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `marca_id` INT NOT NULL,
  PRIMARY KEY (`id`, `marca_id`),
  INDEX `fk_modelos_marcas_idx` (`marca_id` ASC),
  CONSTRAINT `fk_modelos_marcas`
    FOREIGN KEY (`marca_id`)
    REFERENCES `YoLoArreglo`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YoLoArreglo`.`tutorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YoLoArreglo`.`tutorial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(500) NULL,
  `modelo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `modelo_id`),
  INDEX `fk_tutorial_modelos1_idx` (`modelo_id` ASC),
  CONSTRAINT `fk_tutorial_modelos1`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `YoLoArreglo`.`modelos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YoLoArreglo`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YoLoArreglo`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YoLoArreglo`.`informacionContacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YoLoArreglo`.`informacionContacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cuentaFacebook` VARCHAR(45) NULL,
  `cuentaTwitter` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `yoloarreglo`.`informacioncontacto` (`cuentaFacebook`, `cuentaTwitter`, `telefono`, `correo`) VALUES ('https://www.facebook.com/YoLoArreglo', 'https://twitter.com/YoLoArreglo', '(667) 1-522-554', 'Contacto@YoLoArreglo.com.mx');

INSERT INTO `yoloarreglo`.`marcas` (`nombre`) VALUES ('Samsumg');
INSERT INTO `yoloarreglo`.`marcas` (`nombre`) VALUES ('LG');
INSERT INTO `yoloarreglo`.`marcas` (`nombre`) VALUES ('Asus');
INSERT INTO `yoloarreglo`.`marcas` (`nombre`) VALUES ('Motorola');

INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('Samsung Captivate Glide', '1');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('Samsung Captivate', '1');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('LG Optimus V', '2');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('LG Ally VS740', '2');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('Asus Padfone 2', '3');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('Asus PadFone S', '3');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('Motorola Atrix 4G', '4');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('Motorola Cliq', '4');