-- MySQL Script generated by MySQL Workbench
-- 05/31/15 13:22:29
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema YoLoArreglo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `YoLoArreglo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `YoLoArreglo` ;

-- -----------------------------------------------------
-- Table `YoLoArreglo`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YoLoArreglo`.`marcas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YoLoArreglo`.`modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YoLoArreglo`.`modelos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `marca_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modelos_marcas_idx` (`marca_id` ASC),
  CONSTRAINT `fk_modelos_marcas`
    FOREIGN KEY (`marca_id`)
    REFERENCES `YoLoArreglo`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YoLoArreglo`.`tutoriales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YoLoArreglo`.`tutoriales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(500) NULL,
  `img` VARCHAR(100) NULL,
  `modelo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tutorial_modelos1_idx` (`modelo_id` ASC),
  CONSTRAINT `fk_tutorial_modelos1`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `YoLoArreglo`.`modelos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YoLoArreglo`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YoLoArreglo`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YoLoArreglo`.`informacionContacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YoLoArreglo`.`informacionContacto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cuentaFacebook` VARCHAR(45) NULL,
  `cuentaTwitter` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `YoLoArreglo`.`pasos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `YoLoArreglo`.`pasos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(255) NULL,
  `tutorial_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pasos_tutoriales1_idx` (`tutorial_id` ASC),
  CONSTRAINT `fk_pasos_tutoriales1`
    FOREIGN KEY (`tutorial_id`)
    REFERENCES `YoLoArreglo`.`tutoriales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `yoloarreglo`.`informacioncontacto` (`cuentaFacebook`, `cuentaTwitter`, `telefono`, `correo`) VALUES ('https://www.facebook.com/YoLoArreglo', 'https://twitter.com/YoLoArreglo', '(667) 1-522-554', 'Contacto@YoLoArreglo.com.mx');

INSERT INTO `yoloarreglo`.`marcas` (`nombre`) VALUES ('Samsumg');
INSERT INTO `yoloarreglo`.`marcas` (`nombre`) VALUES ('LG');
INSERT INTO `yoloarreglo`.`marcas` (`nombre`) VALUES ('Asus');
INSERT INTO `yoloarreglo`.`marcas` (`nombre`) VALUES ('Motorola');

INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('Samsung Captivate Glide', '1');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('Samsung Captivate', '1');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('LG Optimus V', '2');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('LG Ally VS740', '2');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('Asus Padfone 2', '3');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('Asus PadFone S', '3');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('Motorola Atrix 4G', '4');
INSERT INTO `yoloarreglo`.`modelos` (`nombre`, `marca_id`) VALUES ('Motorola Cliq', '4');

INSERT INTO `yoloarreglo`.`tutoriales` (`nombre`, `descripcion`, `img`, `modelo_id`) VALUES ('Desensamblaje', 'El Samsung Captivate Glide es un dispositivo bastante fácil de desmontar y reparar. Sólo se necesita una sola punta del destornillador y las partes son todas modulares y puede ser reemplazado fácilmente.', 'desmontar.png', '1');
INSERT INTO `yoloarreglo`.`tutoriales` (`nombre`, `descripcion`, `img`, `modelo_id`) VALUES ('Reemplazo de pantalla', 'Como reemplazar una pantalla del Samsung Captivate Glide.', 'remplazo.png', '1');

INSERT INTO `yoloarreglo`.`pasos` (`nombre`, `descripcion`, `tutorial_id`) VALUES ('Paso 1', 'Primero retire la batería.', '1');
INSERT INTO `yoloarreglo`.`pasos` (`nombre`, `descripcion`, `tutorial_id`) VALUES ('Paso 2', 'Con el destornillador Phillips # 00 quite los siete tornillos.', '1');
INSERT INTO `yoloarreglo`.`pasos` (`nombre`, `descripcion`, `tutorial_id`) VALUES ('Paso 3', 'Utilizando una herramienta de abertura de plástico labios más amplia palanca el exterior de la vivienda y la parte posterior eliminará limpiamente.', '1');
INSERT INTO `yoloarreglo`.`pasos` (`nombre`, `descripcion`, `tutorial_id`) VALUES ('Paso 4', 'Con el fin de eliminar la placa base eliminar un solo tornillo con el destornillador Phillips # 00, levante suavemente los dos conectores del pop en el tablero, y finalmente lograr el cable coaxial.', '1');
INSERT INTO `yoloarreglo`.`pasos` (`nombre`, `descripcion`, `tutorial_id`) VALUES ('Paso 5', 'La bocina también se elimina fácilmente tirando hacia arriba del conector de pop.', '1');
INSERT INTO `yoloarreglo`.`pasos` (`nombre`, `descripcion`, `tutorial_id`) VALUES ('Paso 6', 'El módulo de antena puede ser eliminado desconectando el cable coaxial y un solo tornillo phillips # 00.', '1');
INSERT INTO `yoloarreglo`.`pasos` (`nombre`, `descripcion`, `tutorial_id`) VALUES ('Paso 1', 'Retire la cubierta posterior usando la uña o plástico herramienta de apertura. La tapa se levanta y se apaga.', '2');
INSERT INTO `yoloarreglo`.`pasos` (`nombre`, `descripcion`, `tutorial_id`) VALUES ('Paso 2', 'Remove battery with plastic opening tool or finger.', '2');
INSERT INTO `yoloarreglo`.`pasos` (`nombre`, `descripcion`, `tutorial_id`) VALUES ('Paso 3', 'Retire los siete tornillos de la placa trasera con el destornillador # 00.', '2');
INSERT INTO `yoloarreglo`.`pasos` (`nombre`, `descripcion`, `tutorial_id`) VALUES ('Paso 4', 'Con la herramienta de abertura de plástico, retire la placa posterior haciendo palanca en los cuatro puntos principales.', '2');
INSERT INTO `yoloarreglo`.`pasos` (`nombre`, `descripcion`, `tutorial_id`) VALUES ('Paso 5', 'Con la herramienta de abertura de plástico para hacer palanca alrededor de los bordes, suelte la pantalla táctil del marco de la pantalla.', '2');
INSERT INTO `yoloarreglo`.`pasos` (`nombre`, `descripcion`, `tutorial_id`) VALUES ('Paso 6', 'Mientras el adhesivo está todavía caliente, utilice la herramienta de abertura de plástico para eliminar suavemente el cable de la flexión del teclado de la pantalla.', '2');

INSERT INTO `yoloarreglo`.`usuarios` (`nombreUsuario`, `password`, `nombre`) VALUES ('franciscoapp', '1234', 'Francisco Antonio');
